const fs = require('fs');
const path = require('path');
const {
    execSync
} = require('child_process');

const C_RESET = "\x1b[0m";
const C_GREEN = "\x1b[32m";
const C_CYAN = "\x1b[36m";
const C_YELLOW = "\x1b[33m";
const C_RED = "\x1b[31m";

console.log(`${C_CYAN}=================================================${C_RESET}`);
console.log(`${C_CYAN}  🛡️  AegisWasm - Compilador Maestro (Fase 2)   ${C_RESET}`);
console.log(`${C_CYAN}=================================================\n${C_RESET}`);

// 1. Cargar el contrato
const targetDir = process.argv[2] || process.cwd();
const configPath = path.join(targetDir, 'aegis.config.json');

if (!fs.existsSync(configPath)) {
    console.error(`${C_RED}❌ Error: No se encontró el contrato aegis.config.json en ${targetDir}${C_RESET}`);
    process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
const XOR_KEY = config.options.xor_key || 90;
const outDir = path.join(targetDir, config.options.out_dir || 'dist');

// 2. Preparar el entorno de despliegue (dist)
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, {
        recursive: true
    });
}
const binDir = path.join(outDir, 'bin');
if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, {
        recursive: true
    });
}

// 3. Unificar todos los activos que van a la Bóveda
const vaultAssets = [...(config.encrypt || []), ...(config.workers || [])];

let headerLines = [
    "// Auto-generated by AegisWasm Build Pipeline",
    "#ifndef ENCRYPTED_CODE_H",
    "#define ENCRYPTED_CODE_H",
    "",
    "#include <stdint.h>",
    "#include <stddef.h>",
    "",
    "typedef struct {",
    "    const char* filename;",
    "    const uint8_t* bytecode;",
    "    size_t length;",
    "} SecureAsset;",
    ""
];

let arraysContent = [];
let assetsRegistry = [];

console.log(`${C_YELLOW}📦 Empaquetando Bóveda Segura en C++...${C_RESET}`);

vaultAssets.forEach((filePath, idx) => {
    if (!fs.existsSync(filePath)) {
        console.error(`${C_RED}⚠️ Advertencia: Archivo no encontrado - ${filePath}${C_RESET}`);
        return;
    }
    const filename = path.basename(filePath);
    const rawCode = fs.readFileSync(filePath);

    // Cifrado Simétrico XOR Byte por Byte
    let encrypted = new Uint8Array(rawCode.length);
    for (let i = 0; i < rawCode.length; i++) {
        encrypted[i] = rawCode[i] ^ XOR_KEY;
    }

    const hexArray = Array.from(encrypted).map(b => `0x${b.toString(16).padStart(2, '0')}`).join(', ');
    const arrayName = `ENCRYPTED_BYTECODE_${idx}`;

    arraysContent.push(`const uint8_t ${arrayName}[] = {${hexArray}};`);
    assetsRegistry.push(`    {"${filename}", ${arrayName}, ${encrypted.length}}`);

    console.log(`   🔒 Cifrado e inyectado: ${filename}`);
});

headerLines.push(...arraysContent);
headerLines.push("");
headerLines.push(`const SecureAsset SECURE_ASSETS[] = {`);
headerLines.push(assetsRegistry.join(',\n'));
headerLines.push(`};`);
headerLines.push(`const size_t SECURE_ASSETS_COUNT = ${assetsRegistry.length};`);
headerLines.push(`const uint8_t XOR_KEY = ${XOR_KEY};`);
headerLines.push("");
headerLines.push("#endif");

// 4. Escribir el catálogo en el motor C++ (Ruta absoluta relativa al script)
const coreDir = path.join(__dirname, '..', 'core');
const headerPath = path.join(coreDir, 'encrypted_code.h');
fs.writeFileSync(headerPath, headerLines.join('\n'));
console.log(`\n✅ Catálogo Wasm regenerado en: ${headerPath}`);

// 5. Trasladar y blindar automáticamente archivos de la Zona Roja (Ej: sw.js) sin tocar el original
console.log(`\n${C_YELLOW}📂 Procesando y blindando archivos de la Zona Roja...${C_RESET}`);
(config.exclude || []).forEach(filePath => {
    if (fs.existsSync(filePath)) {
        const filename = path.basename(filePath);
        const dest = path.join(outDir, filename);

        let content = fs.readFileSync(filePath, 'utf-8');

        // Si el archivo es un Service Worker, le inyectamos el bypass de red automáticamente al compilar
        if (filename.includes('sw.js')) {
            // ═══════════════════════════════════════════════════════════════
            // FIX 1 + FIX 2: Bypass de red con la excepción de .m4s de R2
            // ═══════════════════════════════════════════════════════════════
            const bypassSnippet = `
            // [AegisWasm Auto-Bypass Inyectado por el Compilador]
            // FIX 1: el handler fetch recibe 'e' (no 'event').
            // FIX 2: Los .m4s de R2 son SAGRADOS. Deben caer SIEMPRE al interceptor de bóveda
            //        táctica, incluso si traen cabecera Range (que Hls.js usa por defecto).
            const url = new URL(e.request.url);
            const isR2Segment = url.hostname.includes('r2.dev') && url.pathname.endsWith('.m4s');
            if (!isR2Segment && (url.hostname.includes('r2.dev') || e.request.destination === 'audio' || url.pathname.match(/\\.(flac|wav|mp3|m4a)$/i) || e.request.headers.has('range'))) {
                return;
            }
            `;

            const regex = /self\.addEventListener\s*\(\s*['"]fetch['"]\s*,\s*(?:async\s*)?\(([^)]+)\)\s*=>\s*\{/i;
            if (regex.test(content)) {
                content = content.replace(regex, (match) => `${match}\n${bypassSnippet}`);
                console.log(`   🛡️ Bypass de streaming y R2 inyectado automáticamente en: ${filename}`);
            } else {
                console.log(`   ⚠️ No se detectó 'fetch' en ${filename}, se copió sin alteraciones.`);
            }

            // ═══════════════════════════════════════════════════════════════
            // FIX 3: Purgar ASSETS_TO_CACHE — eliminar los archivos que
            // AegisWasm movió a la bóveda Wasm (ya no existen en dist/),
            // para evitar que cache.addAll falle y mate la instalación.
            // ═══════════════════════════════════════════════════════════════
            const vaultBasenames = new Set();
            vaultAssets.forEach(p => vaultBasenames.add(path.basename(p)));

            const assetsRegex = /const\s+ASSETS_TO_CACHE\s*=\s*\[([\s\S]*?)\];/;
            const assetsMatch = content.match(assetsRegex);
            if (assetsMatch) {
                const originalEntries = assetsMatch[1]
                    .split(',')
                    .map(s => s.trim())
                    .filter(s => s.length > 0);

                const filteredEntries = originalEntries.filter(entry => {
                    const cleaned = entry.replace(/['"]/g, '').trim();
                    const base = cleaned.split('/').pop();
                    return !vaultBasenames.has(base);
                });

                const removed = originalEntries.length - filteredEntries.length;
                const newArray = `const ASSETS_TO_CACHE = [\n    ${filteredEntries.join(',\n    ')}\n];`;
                content = content.replace(assetsRegex, newArray);
                console.log(`   🧹 ASSETS_TO_CACHE limpiado: ${removed} activo(s) movido(s) a la bóveda fueron excluidos del precache.`);
            } else {
                console.log(`   ⚠️ No se encontró ASSETS_TO_CACHE en ${filename}, se copió sin filtrar.`);
            }
        }

        fs.writeFileSync(dest, content, 'utf-8');
        console.log(`   📄 Desplegado en dist/: ${filename}`);
    }
});

console.log(`\n${C_GREEN}🚀 Fase 2 completada exitosamente. Bóveda empaquetada.${C_RESET}`);
console.log(`\nPara generar el binario final en tu carpeta 'dist', corre este comando de Emscripten:\n`);

// Mostramos el comando de Emscripten ya formateado para que apunte a la nueva carpeta dist
const wslBinDir = binDir.replace(/\\/g, '/');
const wslCoreDir = coreDir.replace(/\\/g, '/');
console.log(`${C_CYAN}em++ "${wslCoreDir}/vm_core.cpp" -O3 -s WASM=1 -s EXPORTED_FUNCTIONS="['_execute_secure_logic','_get_secure_asset','_free_secure_asset']" -s EXPORTED_RUNTIME_METHODS="['cwrap', 'ccall', 'UTF8ToString']" -s MODULARIZE=1 -s EXPORT_ES6=1 -o "${wslBinDir}/aegis_engine.js"${C_RESET}\n`);