const fs = require('fs');
const path = require('path');
const {
    execSync
} = require('child_process');

const C_RESET = "\x1b[0m";
const C_GREEN = "\x1b[32m";
const C_CYAN = "\x1b[36m";
const C_YELLOW = "\x1b[33m";
const C_RED = "\x1b[31m";

console.log(`${C_CYAN}=================================================${C_RESET}`);
console.log(`${C_CYAN}  🛡️  AegisWasm - Compilador Maestro (Fase 2)   ${C_RESET}`);
console.log(`${C_CYAN}=================================================\n${C_RESET}`);

// 1. Cargar el contrato
const targetDir = process.argv[2] || process.cwd();
const configPath = path.join(targetDir, 'aegis.config.json');

if (!fs.existsSync(configPath)) {
    console.error(`${C_RED}❌ Error: No se encontró el contrato aegis.config.json en ${targetDir}${C_RESET}`);
    process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
const XOR_KEY = config.options.xor_key || 90;
const outDir = path.join(targetDir, config.options.out_dir || 'dist');

// 2. Preparar el entorno de despliegue (dist)
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, {
        recursive: true
    });
}
const binDir = path.join(outDir, 'bin');
if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, {
        recursive: true
    });
}

// 3. Normalización inteligente de rutas (Soporte nativo para rutas relativas y absolutas)
const resolveAssetPath = (p) => path.isAbsolute(p) ? p : path.resolve(targetDir, p);

const encryptAssets = (config.encrypt || []).map(resolveAssetPath);
const workerAssets = (config.workers || []).map(resolveAssetPath);
const excludeAssets = (config.exclude || []).map(resolveAssetPath);

const vaultAssets = [...encryptAssets, ...workerAssets];

let headerLines = [
    "// Auto-generated by AegisWasm Build Pipeline",
    "#ifndef ENCRYPTED_CODE_H",
    "#define ENCRYPTED_CODE_H",
    "",
    "#include <stdint.h>",
    "#include <stddef.h>",
    "",
    "typedef struct {",
    "    const char* filename;",
    "    const uint8_t* bytecode;",
    "    size_t length;",
    "} SecureAsset;",
    ""
];

let arraysContent = [];
let assetsRegistry = [];

console.log(`${C_YELLOW}📦 Empaquetando Bóveda Segura en C++...${C_RESET}`);

vaultAssets.forEach((filePath, idx) => {
    if (!fs.existsSync(filePath)) {
        console.error(`${C_RED}⚠️ Advertencia: Archivo no encontrado - ${filePath}${C_RESET}`);
        return;
    }
    const filename = path.basename(filePath);
    const rawCode = fs.readFileSync(filePath);

    // Cifrado Simétrico XOR Byte por Byte
    let encrypted = new Uint8Array(rawCode.length);
    for (let i = 0; i < rawCode.length; i++) {
        encrypted[i] = rawCode[i] ^ XOR_KEY;
    }

    const hexArray = Array.from(encrypted).map(b => `0x${b.toString(16).padStart(2, '0')}`).join(', ');
    const arrayName = `ENCRYPTED_BYTECODE_${idx}`;

    arraysContent.push(`const uint8_t ${arrayName}[] = {${hexArray}};`);
    assetsRegistry.push(`    {"${filename}", ${arrayName}, ${encrypted.length}}`);

    console.log(`   🔒 Cifrado e inyectado: ${filename}`);
});

headerLines.push(...arraysContent);
headerLines.push("");
headerLines.push(`const SecureAsset SECURE_ASSETS[] = {`);
headerLines.push(assetsRegistry.join(',\n'));
headerLines.push(`};`);
headerLines.push(`const size_t SECURE_ASSETS_COUNT = ${assetsRegistry.length};`);
headerLines.push(`const uint8_t XOR_KEY = ${XOR_KEY};`);
headerLines.push("");
headerLines.push("#endif");

// 4. Escribir el catálogo en el motor C++ (Ruta absoluta relativa al script)
const coreDir = path.join(__dirname, '..', 'core');
const headerPath = path.join(coreDir, 'encrypted_code.h');
fs.writeFileSync(headerPath, headerLines.join('\n'));
console.log(`\n✅ Catálogo Wasm regenerado en: ${headerPath}`);

// 5. Generar la Arquitectura Adapter (Nivel 2)
console.log(`\n${C_YELLOW}📂 Fase 3: Construyendo Manifiesto y conectando el Adapter...${C_RESET}`);

// A) Construir el Manifiesto ("La Lista VIP")
const vaultBasenames = vaultAssets.map(p => path.basename(p));
const manifest = {
    aegis_version: "2.0",
    build_timestamp: new Date().toISOString(),
    crypto: {
        algorithm: "xor",
        key: XOR_KEY
    },
    vault_assets: vaultBasenames,
    routing: [{
            id: "r2-audio-segments",
            match_hostname: "r2.dev",
            match_path: "\\.m4s$",
            transform: "/v-enc/"
        },
        {
            id: "hf-audio-segments",
            match_hostname: "workers.dev",
            match_path: "\\.m4s$",
            transform: "/v-enc/"
        }
    ]
};

const manifestPath = path.join(outDir, 'aegis.manifest.json');
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 4));
console.log(`   📜 Manifiesto VIP generado exitosamente: aegis.manifest.json`);

// B) AUTO-INSTALACIÓN DEL GUARDAESPALDAS (aegis-sw-adapter.js)
const adapterCode = `
// ============================================================================
// 🛡️ AegisWasm - Adapter Pattern (Auto-Generado por el Compilador)
// ============================================================================
self.AegisAdapter = (function() {
    let manifest = null;
    fetch('/aegis.manifest.json')
        .then(res => res.json())
        .then(data => manifest = data)
        .catch(err => console.error('[🛡️ Aegis] Error cargando manifiesto:', err));

    function decryptXOR(buffer, key) {
        const data = new Uint8Array(buffer);
        const limit = Math.min(100, data.length);
        for (let i = 0; i < limit; i++) data[i] ^= key;
        return data.buffer;
    }

    return {
        handle: function(event) {
            const url = new URL(event.request.url);
            if (event.request.method !== 'GET' || !url.protocol.startsWith('http') || !url.pathname.endsWith('.m4s')) {
                return false;
            }

            event.respondWith((async () => {
                if (!manifest) {
                    try {
                        const res = await fetch('/aegis.manifest.json');
                        manifest = await res.json();
                    } catch(e) { return fetch(event.request); }
                }

                const rule = manifest.routing.find(r =>
                    url.hostname.includes(r.match_hostname) && new RegExp(r.match_path).test(url.pathname)
                );
                if (!rule) return fetch(event.request);

                const pathParts = url.pathname.split('/');
                const fileName = pathParts.pop();
                const newPath = pathParts.join('/') + rule.transform + fileName + '.enc';
                const encUrl = url.origin + newPath;

                try {
                    const encResponse = await fetch(encUrl);
                    if (!encResponse.ok) return fetch(event.request);

                    const buffer = await encResponse.arrayBuffer();
                    const decryptedBuffer = decryptXOR(buffer, manifest.crypto.key);
                    return new Response(decryptedBuffer, {
                        status: 200,
                        headers: { 'Content-Type': 'video/iso.segment' }
                    });
                } catch (err) { return fetch(event.request); }
            })());
            return true;
        }
    };
})();
`;
const adapterPath = path.join(outDir, 'aegis-sw-adapter.js');
fs.writeFileSync(adapterPath, adapterCode.trim(), 'utf-8');
console.log(`   💂 Guardaespaldas auto-generado: aegis-sw-adapter.js`);

// C) Trasladar archivos de la Zona Roja e Inyectar el Adapter
excludeAssets.forEach(filePath => {
    if (fs.existsSync(filePath)) {
        const filename = path.basename(filePath);
        const dest = path.join(outDir, filename);
        let content = fs.readFileSync(filePath, 'utf-8');

        if (filename.includes('sw.js')) {
            const importAdapter = "importScripts('/aegis-sw-adapter.js');\n";
            const handlerHook = "\n    if (self.AegisAdapter && self.AegisAdapter.handle(e)) return;\n";

            // 1. Inyectamos en la línea 1
            if (!content.includes('aegis-sw-adapter.js')) {
                content = importAdapter + content;
            }

            // 2. Inyectamos silenciosamente justo después de abrir el fetch original
            const fetchRegex = /(self\.addEventListener\s*\(\s*['"]fetch['"]\s*,\s*(?:async\s*)?\(([^)]+)\)\s*=>\s*\{)/i;
            if (fetchRegex.test(content) && !content.includes('AegisAdapter.handle')) {
                // Reemplazamos la captura del Regex agregando nuestro "hook" sin romper nada más
                content = content.replace(fetchRegex, (match, p1, p2) => {
                    // Reemplazamos 'e' por el nombre de variable que use el programador original (p2)
                    const dynamicHook = handlerHook.replace(/\(e\)/g, `(${p2.trim()})`);
                    return p1 + dynamicHook;
                });
                console.log(`   🛡️ Inyección limpia: El Guardaespaldas vigila la puerta en ${filename}`);
            }
        }

        fs.writeFileSync(dest, content, 'utf-8');
        const displayOutDir = config.options.out_dir || './';
        console.log(`   📄 Desplegado limpio en ${displayOutDir}: ${filename}`);
    }
});

console.log(`\n${C_GREEN}🚀 Fase 2 completada: Manifiesto, Adapter y Bóveda C++ preparados.${C_RESET}`);
console.log(`${C_YELLOW}⚙️ Compilando motor WebAssembly automáticamente...${C_RESET}`);

try {
    const coreDir = path.join(__dirname, '..', 'core');
    const wslCoreDir = coreDir.replace(/\\/g, '/');
    const targetBinDir = binDir.replace(/\\/g, '/');

    const emscriptenCmd = `em++ "${wslCoreDir}/vm_core.cpp" -O3 -s WASM=1 -s EXPORTED_FUNCTIONS="['_execute_secure_logic','_get_secure_asset','_free_secure_asset']" -s EXPORTED_RUNTIME_METHODS="['cwrap', 'ccall', 'UTF8ToString']" -s MODULARIZE=1 -s EXPORT_ES6=1 -o "${targetBinDir}/aegis_engine.js"`;

    execSync(emscriptenCmd, {
        stdio: 'inherit'
    });
    console.log(`\n${C_GREEN}✨ ¡ÉXITO TOTAL! Motor Wasm compilado e instalado en tu proyecto.${C_RESET}`);
} catch (err) {
    console.error(`${C_RED}❌ Error al compilar con Emscripten. Asegúrate de tener em++ en el PATH.${C_RESET}`, err.message);
}

// 6. Automatización inteligente del .gitignore con delimitadores de inicio y fin (Resiliente a cualquier posición)
const gitignorePath = path.join(targetDir, '.gitignore');
const gitDir = path.join(targetDir, '.git');

if (fs.existsSync(gitDir)) {
    const startMarker = '# --- AEGISWASM_BLOCK_START ---';
    const endMarker = '# --- AEGISWASM_BLOCK_END ---';

    const filesToIgnore = vaultAssets.map(p => path.relative(targetDir, p).replace(/\\/g, '/')).join('\n');
    const targetBlock = `${startMarker}\n# ==========================================================================\n# encrypt by AegisWasm\n# ==========================================================================\n${filesToIgnore}\n${endMarker}`;

    let gitignoreData = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf-8') : '';

    // Expresión regular robusta para ubicar el bloque exacto sin importar si está al inicio, medio o final
    const escapedStart = startMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const escapedEnd = endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const blockRegex = new RegExp(`${escapedStart}[\\s\\S]*?${escapedEnd}`, 'g');

    if (blockRegex.test(gitignoreData)) {
        // Reemplaza quirúrgicamente el bloque existente donde sea que se encuentre
        gitignoreData = gitignoreData.replace(blockRegex, targetBlock);
    } else {
        // Si no existe, lo adjunta limpiamente al final
        gitignoreData = gitignoreData.trim() + '\n\n' + targetBlock + '\n';
    }

    fs.writeFileSync(gitignorePath, gitignoreData.trim() + '\n', 'utf-8');
    console.log(`   🛡️ .gitignore actualizado automáticamente con los activos de la bóveda.`);

    try {
        const trackedFiles = vaultAssets.map(p => path.relative(targetDir, p)).filter(filePath => {
            try {
                execSync(`git ls-files --error-match "${filePath}"`, {
                    cwd: targetDir,
                    stdio: 'ignore'
                });
                return true;
            } catch {
                return false;
            }
        });

        if (trackedFiles.length > 0) {
            console.log(`\n${C_YELLOW}⚠️ [AegisWasm Security Notice] Los siguientes archivos encriptados siguen rastreados por Git:${C_RESET}`);
            trackedFiles.forEach(f => console.log(`   - ${f.replace(/\\/g, '/')}`));
            console.log(`💡 Para purgarlos de la nube (GitHub) sin perderlos de tu PC, ejecuta una sola vez:`);
            console.log(`   git rm --cached ${trackedFiles.map(f => `"${f.replace(/\\/g, '/')}"`).join(' ')}`);
        }
    } catch (gitErr) {
        // Ignorar silenciosamente si hay problemas de ejecución con Git
    }
}