const fs = require('fs');
const path = require('path');
const {
    execSync
} = require('child_process');

const C_RESET = "\x1b[0m";
const C_GREEN = "\x1b[32m";
const C_CYAN = "\x1b[36m";
const C_YELLOW = "\x1b[33m";
const C_RED = "\x1b[31m";

console.log(`${C_CYAN}=================================================${C_RESET}`);
console.log(`${C_CYAN}  🛡️  AegisWasm - Compilador Maestro (Fase 2)   ${C_RESET}`);
console.log(`${C_CYAN}=================================================\n${C_RESET}`);

// 1. Cargar el contrato
const targetDir = process.argv[2] || process.cwd();
const configPath = path.join(targetDir, 'aegis.config.json');

if (!fs.existsSync(configPath)) {
    console.error(`${C_RED}❌ Error: No se encontró el contrato aegis.config.json en ${targetDir}${C_RESET}`);
    process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
const XOR_KEY = config.options.xor_key || 90;
const outDir = path.join(targetDir, config.options.out_dir || 'dist');
const sourceDir = path.join(targetDir, config.source_dir || './encript');

// ═══════════════════════════════════════════════════════════════════════════
// AUTO-MIGRACIÓN IDEMPOTENTE
// El compilador detecta fuentes en la superficie pública, las mueve a
// source_dir, y deja stubs en su lugar. Al segundo build no hace nada porque
// ya detecta el stub. El usuario nunca mueve archivos a mano.
// ═══════════════════════════════════════════════════════════════════════════
if (!fs.existsSync(sourceDir)) {
    fs.mkdirSync(sourceDir, {
        recursive: true
    });
    console.log(`${C_YELLOW}📁 source_dir creado: ${path.relative(targetDir, sourceDir)}${C_RESET}`);
}

const STUB_MARKER = '// AEGIS-STUB-v1';

function isAegisStub(content) {
    return typeof content === 'string' && content.startsWith(STUB_MARKER);
}

function findOriginalInPublic(name) {
    // Busca el original en candidatos: targetDir raíz y outDir.
    const candidates = [
        path.join(targetDir, name),
        path.join(outDir, name)
    ];
    const unique = [...new Set(candidates.map(p => path.resolve(p)))];
    for (const p of unique) {
        if (fs.existsSync(p)) {
            const content = fs.readFileSync(p, 'utf-8');
            if (!isAegisStub(content)) return p;
        }
    }
    return null;
}

function ensureSourceMigrated(name) {
    const sourcePath = path.join(sourceDir, name);
    if (fs.existsSync(sourcePath)) return sourcePath;

    const originalPath = findOriginalInPublic(name);
    if (!originalPath) return null;

    fs.renameSync(originalPath, sourcePath);
    console.log(`   🚚 Auto-migración: ${name} → ${path.relative(targetDir, sourcePath)}`);
    return sourcePath;
}

// 2. Preparar el entorno de despliegue (dist)
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, {
        recursive: true
    });
}
const binDir = path.join(outDir, 'bin');
if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, {
        recursive: true
    });
}

// 3. Resolución de rutas bajo el nuevo modelo source_dir/out_dir
//    - encrypt/workers: nombres relativos a source_dir (fuente) y a out_dir (stub)
//    - exclude: nombres relativos a targetDir (archivos intocables)
const publicNames = [
    ...(config.encrypt || []),
    ...(config.workers || [])
];

// Disparamos la auto-migración para cada activo antes de leerlo.
console.log(`${C_YELLOW}🔄 Verificando estado de los activos...${C_RESET}`);
for (const name of publicNames) {
    ensureSourceMigrated(name);
}

// Ahora resolvemos las rutas de LECTURA (source_dir) y de ESCRITURA (out_dir)
const encryptAssets = (config.encrypt || []).map(n => path.join(sourceDir, n));
const workerAssets = (config.workers || []).map(n => path.join(sourceDir, n));
const excludeAssets = (config.exclude || []).map(n => path.resolve(targetDir, n));

const vaultAssets = [...encryptAssets, ...workerAssets];

// Validación temprana: todos los activos deben existir en source_dir
const missingSources = vaultAssets.filter(p => !fs.existsSync(p));
if (missingSources.length > 0) {
    console.error(`${C_RED}❌ Faltan fuentes en ${sourceDir}:${C_RESET}`);
    missingSources.forEach(p => console.error(`   - ${path.relative(targetDir, p)}`));
    console.error(`${C_YELLOW}💡 Copia los originales a ${path.relative(targetDir, sourceDir)} y vuelve a intentar.${C_RESET}`);
    process.exit(1);
}

let headerLines = [
    "// Auto-generated by AegisWasm Build Pipeline",
    "#ifndef ENCRYPTED_CODE_H",
    "#define ENCRYPTED_CODE_H",
    "",
    "#include <stdint.h>",
    "#include <stddef.h>",
    "",
    "typedef struct {",
    "    const char* filename;",
    "    const uint8_t* bytecode;",
    "    size_t length;",
    "} SecureAsset;",
    ""
];

let arraysContent = [];
let assetsRegistry = [];

console.log(`${C_YELLOW}📦 Empaquetando Bóveda Segura en C++...${C_RESET}`);

vaultAssets.forEach((filePath, idx) => {
    if (!fs.existsSync(filePath)) {
        console.error(`${C_RED}⚠️ Advertencia: Archivo no encontrado - ${filePath}${C_RESET}`);
        return;
    }
    const filename = path.basename(filePath);
    const rawCode = fs.readFileSync(filePath);

    // Cifrado Simétrico XOR Byte por Byte
    let encrypted = new Uint8Array(rawCode.length);
    for (let i = 0; i < rawCode.length; i++) {
        encrypted[i] = rawCode[i] ^ XOR_KEY;
    }

    const hexArray = Array.from(encrypted).map(b => `0x${b.toString(16).padStart(2, '0')}`).join(', ');
    const arrayName = `ENCRYPTED_BYTECODE_${idx}`;

    arraysContent.push(`const uint8_t ${arrayName}[] = {${hexArray}};`);
    assetsRegistry.push(`    {"${filename}", ${arrayName}, ${encrypted.length}}`);

    console.log(`   🔒 Cifrado e inyectado: ${filename}`);
});

headerLines.push(...arraysContent);
headerLines.push("");
headerLines.push(`const SecureAsset SECURE_ASSETS[] = {`);
headerLines.push(assetsRegistry.join(',\n'));
headerLines.push(`};`);
headerLines.push(`const size_t SECURE_ASSETS_COUNT = ${assetsRegistry.length};`);
headerLines.push(`const uint8_t XOR_KEY = ${XOR_KEY};`);
headerLines.push("");
headerLines.push("#endif");

// 4. Escribir el catálogo en el motor C++ (Ruta absoluta relativa al script)
const coreDir = path.join(__dirname, '..', 'core');
const headerPath = path.join(coreDir, 'encrypted_code.h');
fs.writeFileSync(headerPath, headerLines.join('\n'));
console.log(`\n✅ Catálogo Wasm regenerado en: ${headerPath}`);

// 5. Generar la Arquitectura Adapter (Nivel 2)
console.log(`\n${C_YELLOW}📂 Fase 3: Construyendo Manifiesto y conectando el Adapter...${C_RESET}`);

// A) Construir el Manifiesto ("La Lista VIP")
const vaultBasenames = vaultAssets.map(p => path.basename(p));
// 🎛️ El manifest es un ESPEJO FIEL del contrato del usuario.
// AegisWasm NO conoce algoritmos, claves ni nombres de proyecto.
// Todo lo relacionado con routing/cifrado viene de config.routing.
// Si el usuario no declara routing, el manifest sale con array vacío
// y el adapter no intercepta nada (comportamiento passthrough).
const userRouting = Array.isArray(config.routing) ? config.routing : [];

// Fase 3.1: Clasificamos los activos de la bóveda que son scripts ejecutables.
// El adapter usará esta lista para interceptar <script src="/app.js"> del HTML
// y devolver un loader que dispara el SDK en el main thread.
// Los workers quedan fuera por ahora (Fase 3.2 los tratará con contrato propio).
const localScripts = encryptAssets.map(p => ({
    filename: path.basename(p),
    type: 'script'
}));

// Fase 3.2: Clasificamos los activos de la bóveda que son Web Workers.
// El SDK instalará un interceptor de window.Worker que detecta cuando el
// código de usuario hace `new Worker('/story-worker.js')` y lo sustituye
// transparentemente por un Blob Worker descifrado desde la bóveda.
const localWorkers = workerAssets.map(p => ({
    filename: path.basename(p),
    type: 'worker'
}));

const manifest = {
    aegis_version: "2.0",
    build_timestamp: new Date().toISOString(),
    vault_assets: vaultBasenames,
    local_scripts: localScripts,
    local_workers: localWorkers,
    routing: userRouting
};

const manifestPath = path.join(outDir, 'aegis.manifest.json');
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 4));
console.log(`   📜 Manifiesto VIP generado exitosamente: aegis.manifest.json`);

// B) AUTO-INSTALACIÓN DEL GUARDAESPALDAS (aegis-sw-adapter.js)
const adapterCode = `
// ============================================================================
// 🛡️ AegisWasm - Adapter Pattern (Auto-Generado por el Compilador)
// ============================================================================
self.AegisAdapter = (function() {
    let manifest = null;
    // ⏳ Promesa única de carga: todos los handle() la esperan antes de decidir,
    // eliminando la race condition del primer request (cuando el manifest aún no llegó).
    const manifestReady = fetch('/aegis.manifest.json', { cache: 'no-store' })
        .then(res => res.json())
        .then(data => { manifest = data; return data; })
        .catch(err => { console.error('[🛡️ Aegis] Error cargando manifiesto:', err); return null; });

    // ═══════════════════════════════════════════════════════════════════════
    // REGISTRO DE ALGORITMOS DE DESCIFRADO
    // El adapter consulta este registro por el campo algorithm de cada
    // regla de routing. Para añadir un algoritmo nuevo (AES-GCM, ChaCha20,
    // XOR-rotativo, etc.), solo se agrega una entrada aquí. El compilador
    // NO necesita saber que existe.
    // ═══════════════════════════════════════════════════════════════════════
    const CRYPTO_ENGINES = {
        'xor-multibyte': function(data, cfg) {
            const keyBytes = new TextEncoder().encode(cfg.key_utf8);
            const limit = Math.min(cfg.bytes_to_decrypt || data.length, data.length);
            for (let i = 0; i < limit; i++) {
                data[i] ^= keyBytes[i % keyBytes.length];
            }
            return data;
        },
        'xor-single': function(data, cfg) {
            const limit = Math.min(cfg.bytes_to_decrypt || data.length, data.length);
            const k = cfg.key_byte;
            for (let i = 0; i < limit; i++) data[i] ^= k;
            return data;
        },
        'identity': function(data) {
            return data;
        }
    };

    return {
        handle: function(event) {
            const url = new URL(event.request.url);
            if (event.request.method !== 'GET' || !url.protocol.startsWith('http')) {
                return false;
            }

            // El adapter solo maneja segmentos de audio remotos.
            // Los scripts locales ahora son stubs físicos en la raíz, no los tocamos.
            if (!url.pathname.endsWith('.m4s')) {
                return false;
            }

            event.respondWith((async () => {
                await manifestReady;

                // ── Segmento de audio remoto → Descifrado al vuelo ──
                if (manifest && manifest.routing) {
                    const rule = manifest.routing.find(r =>
                        url.hostname.includes(r.match_hostname) && new RegExp(r.match_path).test(url.pathname)
                    );
                    if (!rule) return fetch(event.request);
                    const pathParts = url.pathname.split('/');
                    const fileName = pathParts.pop();
                    const newPath = pathParts.join('/') + rule.transform + fileName + '.enc';
                    const encUrl = url.origin + newPath;
                    try {
                        const encResponse = await fetch(encUrl);
                        if (!encResponse.ok) return fetch(event.request);
                        const buffer = await encResponse.arrayBuffer();
                        const cryptoCfg = rule.crypto || { algorithm: 'identity' };
                        const engine = CRYPTO_ENGINES[cryptoCfg.algorithm];
                        if (!engine) {
                            console.warn('[🛡️ Aegis] Algoritmo no registrado:', cryptoCfg.algorithm, '- passthrough forzado.');
                            return fetch(event.request);
                        }
                        const decryptedData = engine(new Uint8Array(buffer), cryptoCfg);
                        return new Response(decryptedData.buffer, {
                            status: 200,
                            headers: { 'Content-Type': 'video/iso.segment' }
                        });
                    } catch (err) { return fetch(event.request); }
                }

                // Fallback neutro
                return fetch(event.request);
            })());

            return true;
        }
    };
})();
`;
const adapterPath = path.join(outDir, 'aegis-sw-adapter.js');
fs.writeFileSync(adapterPath, adapterCode.trim(), 'utf-8');
console.log(`   💂 Guardaespaldas auto-generado: aegis-sw-adapter.js`);

// B.2) AUTO-INSTALACIÓN DEL SDK CLIENTE (aegis-sdk.js)
// El SDK vive en el main thread, carga el Wasm y expone la API pública
// para inyectar scripts y crear workers desde la bóveda.
const sdkCode = `
import loadAegisEngine from './bin/aegis_engine.js';

class AegisShield {
    constructor() {
        this.engine = null;
        this.ready = this.init();
    }

    async init() {
        console.log("[🛡️ AegisWasm] Inicializando bóveda asíncrona...");
        this.engine = await loadAegisEngine();
        this._manifestCache = null;
        this._installWorkerInterceptor();
        console.log("[🛡️ AegisWasm] Motor en línea. Listo para servir activos.");
    }

    async _loadManifest() {
        if (this._manifestCache) return this._manifestCache;
        try {
            const res = await fetch('/aegis.manifest.json', { cache: 'no-store' });
            this._manifestCache = await res.json();
        } catch (e) {
            console.warn('[🛡️ AegisWasm] No se pudo cargar el manifest:', e);
            this._manifestCache = { local_workers: [] };
        }
        return this._manifestCache;
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Fase 3.2: Interceptor de window.Worker.
    // Cuando el código de usuario crea un Worker apuntando a un archivo
    // protegido (ej. story-worker.js), devolvemos un Proxy que:
    //   1. Evalúa si el archivo está en manifest.local_workers.
    //   2. Si sí: descifra desde la bóveda y crea un Blob Worker transparente.
    //   3. Si no: delega al Worker original sin tocar nada.
    // Encapsula los mensajes y listeners hasta que el Worker real está listo.
    // ═══════════════════════════════════════════════════════════════════════
    _installWorkerInterceptor() {
        const self_ = this;
        const OriginalWorker = window.Worker;
        if (!OriginalWorker || OriginalWorker.__aegisWrapped) return;

        function AegisWorker(url, options) {
            if (typeof url !== 'string') return new OriginalWorker(url, options);

            const basename = url.split('/').pop().split('?')[0].split('#')[0];

            const state = {
                realWorker: null,
                pendingMessages: [],
                listeners: [],
                onmessage: null,
                onerror: null,
                onmessageerror: null
            };

            self_._loadManifest().then(manifest => {
                const isProtected = manifest.local_workers &&
                    manifest.local_workers.some(w => w.filename === basename);

                const finalize = (real) => {
                    state.realWorker = real;
                    state.listeners.forEach(([t, f, o]) => real.addEventListener(t, f, o));
                    if (state.onmessage) real.onmessage = state.onmessage;
                    if (state.onerror) real.onerror = state.onerror;
                    if (state.onmessageerror) real.onmessageerror = state.onmessageerror;
                    state.pendingMessages.forEach(([m, tr]) => real.postMessage(m, tr));
                    state.pendingMessages.length = 0;
                };

                if (!isProtected) {
                    finalize(new OriginalWorker(url, options));
                    return;
                }

                self_._getRawAsset(basename).then(code => {
                    if (!code) {
                        console.error('[🛡️ AegisWasm] Worker no encontrado en bóveda:', basename);
                        return;
                    }
                    const blob = new Blob([code], { type: 'application/javascript' });
                    const blobUrl = URL.createObjectURL(blob);
                    const realOpts = options || { type: 'module' };
                    finalize(new OriginalWorker(blobUrl, realOpts));
                    console.log('[🛡️ AegisWasm] Worker protegido instanciado desde bóveda: ' + basename);
                });
            });

            return new Proxy({}, {
                get(_, prop) {
                    if (prop === 'postMessage') {
                        return (msg, tr) => {
                            if (state.realWorker) return state.realWorker.postMessage(msg, tr);
                            state.pendingMessages.push([msg, tr]);
                        };
                    }
                    if (prop === 'terminate') {
                        return () => state.realWorker && state.realWorker.terminate();
                    }
                    if (prop === 'addEventListener') {
                        return (t, f, o) => {
                            state.listeners.push([t, f, o]);
                            if (state.realWorker) state.realWorker.addEventListener(t, f, o);
                        };
                    }
                    if (prop === 'removeEventListener') {
                        return (t, f, o) => {
                            state.listeners = state.listeners.filter(
                                ([tt, ff, oo]) => tt !== t || ff !== f || oo !== o
                            );
                            if (state.realWorker) state.realWorker.removeEventListener(t, f, o);
                        };
                    }
                    if (prop === 'onmessage') return state.onmessage;
                    if (prop === 'onerror') return state.onerror;
                    if (prop === 'onmessageerror') return state.onmessageerror;
                    if (state.realWorker) return state.realWorker[prop];
                    return undefined;
                },
                set(_, prop, value) {
                    if (prop === 'onmessage') { state.onmessage = value; if (state.realWorker) state.realWorker.onmessage = value; return true; }
                    if (prop === 'onerror') { state.onerror = value; if (state.realWorker) state.realWorker.onerror = value; return true; }
                    if (prop === 'onmessageerror') { state.onmessageerror = value; if (state.realWorker) state.realWorker.onmessageerror = value; return true; }
                    if (state.realWorker) state.realWorker[prop] = value;
                    return true;
                }
            });
        }

        AegisWorker.prototype = OriginalWorker.prototype;
        AegisWorker.__aegisWrapped = true;
        window.Worker = AegisWorker;
        console.log('[🛡️ AegisWasm] Interceptor de Worker instalado.');
    }

    async _getRawAsset(filename) {
        await this.ready;
        const scriptPtr = this.engine.ccall('get_secure_asset', 'number', ['string'], [filename]);
        if (!scriptPtr) {
            console.error('[🛡️ AegisWasm] Asset no encontrado en bóveda: ' + filename);
            return null;
        }
        const rawCode = this.engine.UTF8ToString(scriptPtr);
        this.engine.ccall('free_secure_asset', null, ['number'], [scriptPtr]);
        return rawCode;
    }

    async injectScript(filename, isModule = false) {
        const code = await this._getRawAsset(filename);
        if (!code) return;

        const script = document.createElement('script');
        if (isModule) script.type = 'module';

        let wrappedCode = code;
        if (document.readyState !== 'loading') {
            // SHIM: si el DOM ya cargó, disparamos DOMContentLoaded inmediatamente
            // para que el callback registrado por el script del usuario se ejecute.
            wrappedCode = '(function(){' +
                'var _origAdd = document.addEventListener;' +
                'document.addEventListener = function(type, listener, opts){' +
                    'if (type === "DOMContentLoaded" && document.readyState !== "loading") {' +
                        'try { listener.call(document, new Event("DOMContentLoaded")); } catch(e) { console.error(e); }' +
                    '} else {' +
                        'return _origAdd.call(document, type, listener, opts);' +
                    '}' +
                '};' +
                'setTimeout(function(){ document.addEventListener = _origAdd; }, 0);' +
            '})();' + '\\n' + code;
        }

        script.textContent = wrappedCode;
        document.head.appendChild(script);
        console.log('[🛡️ AegisWasm] Inyección fantasma completada: ' + filename);
    }

    async createSecureWorker(filename) {
        const code = await this._getRawAsset(filename);
        if (!code) return null;
        const blob = new Blob([code], { type: 'application/javascript' });
        const workerUrl = URL.createObjectURL(blob);
        console.log('[🛡️ AegisWasm] Hilo Worker seguro creado: ' + filename);
        return new Worker(workerUrl, { type: 'module' });
    }
}

export const Aegis = new AegisShield();
window.Aegis = Aegis;
`;
const sdkPath = path.join(outDir, 'aegis-sdk.js');
fs.writeFileSync(sdkPath, sdkCode.trim(), 'utf-8');
console.log(`   🔧 SDK cliente auto-generado: aegis-sdk.js`);


// B.3) GENERADOR DE MICRO-STUBS FÍSICOS EN LA RAÍZ
// El SW nunca controla la página en la carga donde se instala (spec del W3C).
// Si la raíz no tiene archivos y el SW no está activo, el HTML recibe 404 en frío.
// Solución: emitir un stub de ~250 bytes por cada script cifrado. El stub importa
// el SDK, espera a la bóveda, y dispara la inyección fantasma del código real.
// El código fuente real JAMÁS toca el disco en texto plano.
console.log(`${C_YELLOW}🪶 Generando micro-stubs físicos para scripts protegidos...${C_RESET}`);
encryptAssets.forEach(filePath => {
    const filename = path.basename(filePath);
    const stubPath = path.join(outDir, filename);
    const stubCode = `${STUB_MARKER}\n(async()=>{try{const m=await import('/aegis-sdk.js');const A=m.Aegis||window.Aegis;if(!A){console.error('[Aegis Stub] SDK no disponible');return;}await A.ready;await A.injectScript('${filename}');}catch(e){console.error('[Aegis Stub] Fallo en ${filename}:',e);}})();`;
    fs.writeFileSync(stubPath, stubCode, 'utf-8');
    console.log(`   🪶 Stub escrito: ${filename} (${stubCode.length} bytes)`);
});

// C) Trasladar archivos de la Zona Roja e Inyectar el Adapter
excludeAssets.forEach(filePath => {
    if (fs.existsSync(filePath)) {
        const filename = path.basename(filePath);
        const dest = path.join(outDir, filename);
        let content = fs.readFileSync(filePath, 'utf-8');

        if (filename.includes('sw.js')) {
            const importAdapter = "importScripts('/aegis-sw-adapter.js');\n";
            const handlerHook = "\n    if (self.AegisAdapter && self.AegisAdapter.handle(e)) return;\n";

            // 1. Inyectamos en la línea 1
            if (!content.includes('aegis-sw-adapter.js')) {
                content = importAdapter + content;
            }

            // 2. Inyectamos silenciosamente justo después de abrir el fetch original
            const fetchRegex = /(self\.addEventListener\s*\(\s*['"]fetch['"]\s*,\s*(?:async\s*)?\(([^)]+)\)\s*=>\s*\{)/i;
            if (fetchRegex.test(content) && !content.includes('AegisAdapter.handle')) {
                // Reemplazamos la captura del Regex agregando nuestro "hook" sin romper nada más
                content = content.replace(fetchRegex, (match, p1, p2) => {
                    // Reemplazamos 'e' por el nombre de variable que use el programador original (p2)
                    const dynamicHook = handlerHook.replace(/\(e\)/g, `(${p2.trim()})`);
                    return p1 + dynamicHook;
                });
                console.log(`   🛡️ Inyección limpia: El Guardaespaldas vigila la puerta en ${filename}`);
            }

            // 3. Blindar cache.addAll contra 404s de archivos movidos a la bóveda
            //    Transforma: return cache.addAll(ASSETS_TO_CACHE);
            //    En:         return Promise.all(ASSETS_TO_CACHE.map(a => cache.add(a).catch(...)));
            //    Universal: no asume nombres de archivos, funciona en cualquier proyecto.
            const addAllRegex = /return\s+cache\.addAll\s*\(\s*ASSETS_TO_CACHE\s*\)\s*;/;
            if (addAllRegex.test(content)) {
                content = content.replace(
                    addAllRegex,
                    `return Promise.all(ASSETS_TO_CACHE.map(a => cache.add(a).catch(function(err) { console.warn('[AegisWasm] Activo omitido del precache (404, no critico):', a); })));`
                );
                console.log(`   🧹 cache.addAll blindado contra 404s en ${filename}`);
            } else if (content.includes('cache.addAll')) {
                console.log(`   ⚠️ Se detectó 'cache.addAll' pero con un patrón no reconocido. Revisar manualmente.`);
            }
        }

        fs.writeFileSync(dest, content, 'utf-8');
        const displayOutDir = config.options.out_dir || './';
        console.log(`   📄 Desplegado limpio en ${displayOutDir}: ${filename}`);
    }
});

// Verificación de artefactos: confirmar que los 3 archivos críticos existen en outDir
const requiredArtifacts = ['aegis.manifest.json', 'aegis-sw-adapter.js', 'aegis-sdk.js'];
const missingArtifacts = requiredArtifacts.filter(f => !fs.existsSync(path.join(outDir, f)));
if (missingArtifacts.length > 0) {
    console.error(`${C_RED}❌ Faltan artefactos críticos en ${outDir}: ${missingArtifacts.join(', ')}${C_RESET}`);
    process.exit(1);
}
console.log(`   ✅ Verificación: los 3 artefactos core están presentes en ${config.options.out_dir || './'}`);

// Verificación de micro-stubs: confirmar que cada script cifrado tiene su stub físico en la raíz
const missingStubs = encryptAssets
    .map(p => path.basename(p))
    .filter(f => !fs.existsSync(path.join(outDir, f)));
if (missingStubs.length > 0) {
    console.error(`${C_RED}❌ Faltan micro-stubs en ${outDir}: ${missingStubs.join(', ')}${C_RESET}`);
    process.exit(1);
}
console.log(`   ✅ Verificación: los ${encryptAssets.length} micro-stubs están presentes en ${config.options.out_dir || './'}`);

console.log(`\n${C_GREEN}🚀 Fase 2 completada: Manifiesto, Adapter y Bóveda C++ preparados.${C_RESET}`);
console.log(`${C_YELLOW}⚙️ Compilando motor WebAssembly automáticamente...${C_RESET}`);

try {
    const coreDir = path.join(__dirname, '..', 'core');
    const wslCoreDir = coreDir.replace(/\\/g, '/');
    const targetBinDir = binDir.replace(/\\/g, '/');

    const emscriptenCmd = `em++ "${wslCoreDir}/vm_core.cpp" -O3 -s WASM=1 -s EXPORTED_FUNCTIONS="['_execute_secure_logic','_get_secure_asset','_free_secure_asset']" -s EXPORTED_RUNTIME_METHODS="['cwrap', 'ccall', 'UTF8ToString']" -s MODULARIZE=1 -s EXPORT_ES6=1 -o "${targetBinDir}/aegis_engine.js"`;

    execSync(emscriptenCmd, {
        stdio: 'inherit'
    });
    console.log(`\n${C_GREEN}✨ ¡ÉXITO TOTAL! Motor Wasm compilado e instalado en tu proyecto.${C_RESET}`);
} catch (err) {
    console.error(`${C_RED}❌ Error al compilar con Emscripten. Asegúrate de tener em++ en el PATH.${C_RESET}`, err.message);
}

// 6. Automatización inteligente del .gitignore con delimitadores de inicio y fin (Resiliente a cualquier posición)
const gitignorePath = path.join(targetDir, '.gitignore');
const gitDir = path.join(targetDir, '.git');

if (fs.existsSync(gitDir)) {
    const startMarker = '# --- AEGISWASM_BLOCK_START ---';
    const endMarker = '# --- AEGISWASM_BLOCK_END ---';

    const sourceDirRel = path.relative(targetDir, sourceDir).replace(/\\/g, '/');
    const filesToIgnore = [sourceDirRel + '/', ...vaultAssets.map(p => path.relative(targetDir, p).replace(/\\/g, '/'))].join('\n');
    const targetBlock = `${startMarker}\n# ==========================================================================\n# encrypt by AegisWasm\n# ==========================================================================\n${filesToIgnore}\n${endMarker}`;

    let gitignoreData = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf-8') : '';

    // Expresión regular robusta para ubicar el bloque exacto sin importar si está al inicio, medio o final
    const escapedStart = startMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const escapedEnd = endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const blockRegex = new RegExp(`${escapedStart}[\\s\\S]*?${escapedEnd}`, 'g');

    if (blockRegex.test(gitignoreData)) {
        // Reemplaza quirúrgicamente el bloque existente donde sea que se encuentre
        gitignoreData = gitignoreData.replace(blockRegex, targetBlock);
    } else {
        // Si no existe, lo adjunta limpiamente al final
        gitignoreData = gitignoreData.trim() + '\n\n' + targetBlock + '\n';
    }

    fs.writeFileSync(gitignorePath, gitignoreData.trim() + '\n', 'utf-8');
    console.log(`   🛡️ .gitignore actualizado automáticamente con los activos de la bóveda.`);

    try {
        const trackedFiles = vaultAssets.map(p => path.relative(targetDir, p)).filter(filePath => {
            try {
                execSync(`git ls-files --error-unmatch "${filePath}"`, {
                    cwd: targetDir,
                    stdio: 'ignore'
                });
                return true;
            } catch {
                return false;
            }
        });

        if (trackedFiles.length > 0) {
            console.log(`\n${C_YELLOW}⚠️ [AegisWasm Security Notice] Los siguientes archivos encriptados siguen rastreados por Git:${C_RESET}`);
            trackedFiles.forEach(f => console.log(`   - ${f.replace(/\\/g, '/')}`));
            console.log(`💡 Para purgarlos de la nube (GitHub) sin perderlos de tu PC, ejecuta una sola vez:`);
            console.log(`   git rm --cached ${trackedFiles.map(f => `"${f.replace(/\\/g, '/')}"`).join(' ')}`);
        }
    } catch (gitErr) {
        // Ignorar silenciosamente si hay problemas de ejecución con Git
    }
}