import os
import glob

def compile_and_encrypt_all(sources_dir, output_file):
    if not os.path.exists(sources_dir):
        print(f"Error: La carpeta {sources_dir} no existe.")
        return

    # Buscamos todos los archivos .js dentro de la carpeta sources
    js_files = glob.glob(os.path.join(sources_dir, "*.js"))
    if not js_files:
        print(f"No se encontraron archivos .js en {sources_dir}")
        return

    key = 0x5A
    header_lines = [
        "// Auto-generated by AegisWasm Enterprise Encryptor",
        "#ifndef ENCRYPTED_CODE_H",
        "#define ENCRYPTED_CODE_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char* filename;",
        "    const uint8_t* bytecode;",
        "    size_t length;",
        "} SecureAsset;",
        ""
    ]

    arrays_content = []
    assets_registry = []

    for idx, file_path in enumerate(js_files):
        filename = os.path.basename(file_path)
        with open(file_path, 'rb') as f:
            raw_code = f.read()

        # Cifrado XOR para cada archivo
        encrypted = bytes([b ^ key for b in raw_code])
        hex_array = ", ".join([f"0x{b:02X}" for b in encrypted])

        array_name = f"ENCRYPTED_BYTECODE_{idx}"
        arrays_content.append(f"const uint8_t {array_name}[] = {{{hex_array}}};")
        assets_registry.append(f'    {{"{filename}", {array_name}, {len(encrypted)}}}')

    header_lines.extend(arrays_content)
    header_lines.append("")
    header_lines.append(f"const SecureAsset SECURE_ASSETS[] = {{")
    header_lines.extend([f"    {item}," for item in assets_registry])
    header_lines.append("};")
    header_lines.append(f"const size_t SECURE_ASSETS_COUNT = {len(js_files)};")
    header_lines.append(f"const uint8_t XOR_KEY = 0x5A;")
    header_lines.append("")
    header_lines.append("#endif")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n".join(header_lines))

    print(f"[AegisWasm] Se empaquetaron y cifraron {len(js_files)} scripts de forma dinámica en: {output_file}")

if __name__ == "__main__":
    sources_path = "sources"
    output_path = os.path.join("core", "encrypted_code.h")
    compile_and_encrypt_all(sources_path, output_path)